[project]
name = "documentviewer-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
